# Generated by Django 4.0.6 on 2022-08-17 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clanok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.JSONField(blank=True)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('edit_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obrazok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='TopPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('clanok', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.clanok')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, null=True)),
                ('body', models.TextField(null=True)),
                ('clanok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.clanok')),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('edit_date', models.DateField(auto_now=True)),
                ('images', models.ManyToManyField(blank=True, to='base.obrazok')),
            ],
        ),
        migrations.AddField(
            model_name='clanok',
            name='images',
            field=models.ManyToManyField(blank=True, to='base.obrazok'),
        ),
    ]
