# Generated by Django 4.0.6 on 2022-08-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanok',
            name='body',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
