# Generated by Django 4.0.6 on 2022-08-19 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_clanok_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oznamy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clanok', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.clanok')),
            ],
        ),
    ]
